---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-stable
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-canary
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world
